import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Product from '@/models/Product';

const sampleProducts = [
  {
    name: 'Classic Black Oversized T-Shirt',
    slug: 'classic-black-oversized-tshirt',
    description: 'Premium heavyweight cotton oversized tee with a relaxed fit. Perfect for everyday streetwear.',
    category: 'T-Shirts',
    gender: 'Men',
    price: 1299,
    discountPrice: 899,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1503341504253-dff4f94032fc?w=800',
    ],
    sizes: [
      { size: 'S', stock: 15 },
      { size: 'M', stock: 25 },
      { size: 'L', stock: 20 },
      { size: 'XL', stock: 10 },
    ],
    stock: 70,
    tags: ['oversized', 't-shirt', 'black', 'streetwear'],
    isFeatured: true,
    isNewArrival: false,
    careInstructions: 'Machine wash cold. Tumble dry low. Do not bleach.',
  },
  {
    name: 'Vintage Wash Denim Jacket',
    slug: 'vintage-wash-denim-jacket',
    description: 'Timeless denim jacket with vintage wash finish. Button closure with chest pockets.',
    category: 'Jackets',
    gender: 'Unisex',
    price: 3499,
    discountPrice: 2799,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800',
    ],
    sizes: [
      { size: 'S', stock: 8 },
      { size: 'M', stock: 12 },
      { size: 'L', stock: 15 },
      { size: 'XL', stock: 5 },
    ],
    stock: 40,
    tags: ['denim', 'jacket', 'vintage', 'unisex'],
    isFeatured: true,
    isNewArrival: true,
    careInstructions: 'Machine wash cold with like colors. Hang dry.',
  },
  {
    name: 'Midnight Blue Hoodie',
    slug: 'midnight-blue-hoodie',
    description: 'Ultra-soft fleece hoodie in midnight blue. Features kangaroo pocket and adjustable drawstring hood.',
    category: 'Hoodies',
    gender: 'Men',
    price: 2499,
    discountPrice: 1999,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
      'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=800',
    ],
    sizes: [
      { size: 'S', stock: 10 },
      { size: 'M', stock: 18 },
      { size: 'L', stock: 22 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    stock: 62,
    tags: ['hoodie', 'blue', 'fleece', 'winter'],
    isFeatured: true,
    isNewArrival: false,
    careInstructions: 'Machine wash cold. Do not iron on print.',
  },
  {
    name: 'White Minimalist Sneakers',
    slug: 'white-minimalist-sneakers',
    description: 'Clean white leather sneakers with a minimalist design. Comfortable cushioned sole for all-day wear.',
    category: 'Shoes',
    gender: 'Unisex',
    price: 4999,
    discountPrice: 3999,
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800',
    ],
    sizes: [
      { size: '7', stock: 6 },
      { size: '8', stock: 10 },
      { size: '9', stock: 12 },
      { size: '10', stock: 8 },
      { size: '11', stock: 4 },
    ],
    stock: 40,
    tags: ['sneakers', 'white', 'minimalist', 'shoes'],
    isFeatured: true,
    isNewArrival: true,
    careInstructions: 'Wipe clean with damp cloth. Air dry only.',
  },
  {
    name: 'Slim Fit Dark Wash Jeans',
    slug: 'slim-fit-dark-wash-jeans',
    description: 'Premium stretch denim jeans in dark wash. Slim fit with tapered leg for a modern silhouette.',
    category: 'Jeans',
    gender: 'Men',
    price: 2999,
    discountPrice: 2299,
    images: [
      'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=800',
      'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=800',
    ],
    sizes: [
      { size: '28', stock: 5 },
      { size: '30', stock: 12 },
      { size: '32', stock: 18 },
      { size: '34', stock: 10 },
      { size: '36', stock: 5 },
    ],
    stock: 50,
    tags: ['jeans', 'slim-fit', 'dark-wash', 'denim'],
    isFeatured: false,
    isNewArrival: true,
    careInstructions: 'Machine wash cold inside out. Hang dry.',
  },
  {
    name: 'Coral Summer Dress',
    slug: 'coral-summer-dress',
    description: 'Flowy summer dress in coral with delicate floral print. Perfect for warm-weather outings.',
    category: 'Shirts',
    gender: 'Women',
    price: 1999,
    discountPrice: 1599,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
    ],
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 15 },
      { size: 'M', stock: 20 },
      { size: 'L', stock: 10 },
    ],
    stock: 53,
    tags: ['dress', 'summer', 'coral', 'floral', 'women'],
    isFeatured: true,
    isNewArrival: true,
    careInstructions: 'Hand wash cold. Lay flat to dry.',
  },
  {
    name: 'Graphic Print Streetwear Tee',
    slug: 'graphic-print-streetwear-tee',
    description: 'Bold graphic print tee with unique urban artwork. Made from 100% organic cotton.',
    category: 'T-Shirts',
    gender: 'Unisex',
    price: 1499,
    discountPrice: 1099,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
    sizes: [
      { size: 'S', stock: 12 },
      { size: 'M', stock: 20 },
      { size: 'L', stock: 15 },
      { size: 'XL', stock: 8 },
    ],
    stock: 55,
    tags: ['t-shirt', 'graphic', 'streetwear', 'organic'],
    isFeatured: false,
    isNewArrival: true,
    careInstructions: 'Machine wash cold inside out. Do not bleach.',
  },
  {
    name: 'Premium Wool Blend Overcoat',
    slug: 'premium-wool-blend-overcoat',
    description: 'Luxury wool blend overcoat with a tailored fit. Features notch lapel and double-button closure.',
    category: 'Jackets',
    gender: 'Men',
    price: 7999,
    discountPrice: 5999,
    images: [
      'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800',
      'https://images.unsplash.com/photo-1544923246-77307dd270b3?w=800',
    ],
    sizes: [
      { size: 'S', stock: 3 },
      { size: 'M', stock: 6 },
      { size: 'L', stock: 8 },
      { size: 'XL', stock: 4 },
    ],
    stock: 21,
    tags: ['overcoat', 'wool', 'premium', 'formal'],
    isFeatured: true,
    isNewArrival: false,
    careInstructions: 'Dry clean only.',
  },
  {
    name: 'High-Waist Yoga Leggings',
    slug: 'high-waist-yoga-leggings',
    description: 'Buttery-soft high-waist leggings with 4-way stretch. Squat-proof and moisture-wicking.',
    category: 'Jeans',
    gender: 'Women',
    price: 1799,
    discountPrice: 1299,
    images: [
      'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800',
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800',
    ],
    sizes: [
      { size: 'XS', stock: 10 },
      { size: 'S', stock: 18 },
      { size: 'M', stock: 22 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 6 },
    ],
    stock: 68,
    tags: ['leggings', 'yoga', 'women', 'activewear'],
    isFeatured: false,
    isNewArrival: true,
    careInstructions: 'Machine wash cold. Do not use fabric softener.',
  },
  {
    name: 'Retro Running Sneakers',
    slug: 'retro-running-sneakers',
    description: 'Retro-inspired running shoes with modern comfort technology. Colorblock design.',
    category: 'Shoes',
    gender: 'Men',
    price: 5499,
    discountPrice: 4499,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800',
    ],
    sizes: [
      { size: '7', stock: 4 },
      { size: '8', stock: 8 },
      { size: '9', stock: 10 },
      { size: '10', stock: 6 },
      { size: '11', stock: 3 },
    ],
    stock: 31,
    tags: ['sneakers', 'retro', 'running', 'colorblock'],
    isFeatured: true,
    isNewArrival: false,
    careInstructions: 'Spot clean with mild soap. Air dry.',
  },
  {
    name: 'Emerald Satin Blouse',
    slug: 'emerald-satin-blouse',
    description: 'Elegant satin blouse in emerald green. V-neck with subtle draping for a refined look.',
    category: 'Shirts',
    gender: 'Women',
    price: 2299,
    discountPrice: 1899,
    images: [
      'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800',
      'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=800',
    ],
    sizes: [
      { size: 'XS', stock: 5 },
      { size: 'S', stock: 10 },
      { size: 'M', stock: 14 },
      { size: 'L', stock: 8 },
    ],
    stock: 37,
    tags: ['blouse', 'satin', 'emerald', 'women', 'formal'],
    isFeatured: false,
    isNewArrival: true,
    careInstructions: 'Hand wash cold. Iron on low heat inside out.',
  },
  {
    name: 'Camo Print Cargo Joggers',
    slug: 'camo-print-cargo-joggers',
    description: 'Relaxed cargo joggers in camo print. Elastic waistband with multiple utility pockets.',
    category: 'Jeans',
    gender: 'Men',
    price: 2199,
    discountPrice: 1799,
    images: [
      'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=800',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
    ],
    sizes: [
      { size: 'S', stock: 7 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 6 },
    ],
    stock: 40,
    tags: ['joggers', 'cargo', 'camo', 'streetwear'],
    isFeatured: true,
    isNewArrival: false,
    careInstructions: 'Machine wash cold. Tumble dry low.',
  },
  {
    name: 'Pastel Tie-Dye Crop Hoodie',
    slug: 'pastel-tie-dye-crop-hoodie',
    description: 'Trendy cropped hoodie in pastel tie-dye. Soft fleece interior with an oversized fit.',
    category: 'Hoodies',
    gender: 'Women',
    price: 1999,
    discountPrice: 1499,
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    ],
    sizes: [
      { size: 'XS', stock: 6 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 16 },
      { size: 'L', stock: 8 },
    ],
    stock: 42,
    tags: ['hoodie', 'crop', 'tie-dye', 'pastel', 'women'],
    isFeatured: false,
    isNewArrival: true,
    careInstructions: 'Machine wash cold separately. Do not bleach.',
  },
  {
    name: 'Premium Leather Belt',
    slug: 'premium-leather-belt',
    description: 'Handcrafted genuine leather belt with brushed silver buckle. Timeless accessory for any outfit.',
    category: 'Accessories',
    gender: 'Unisex',
    price: 1499,
    discountPrice: 999,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
      'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800',
    ],
    sizes: [
      { size: '30', stock: 10 },
      { size: '32', stock: 15 },
      { size: '34', stock: 12 },
      { size: '36', stock: 8 },
    ],
    stock: 45,
    tags: ['belt', 'leather', 'accessory', 'premium'],
    isFeatured: false,
    isNewArrival: false,
    careInstructions: 'Wipe with leather conditioner. Keep away from water.',
  },
  {
    name: 'Charcoal Grey Slim Fit Shirt',
    slug: 'charcoal-grey-slim-fit-shirt',
    description: 'Modern slim fit shirt in charcoal grey. Spread collar with hidden button-down. Perfect for office or casual.',
    category: 'Shirts',
    gender: 'Men',
    price: 1899,
    discountPrice: 1499,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736c10?w=800',
    ],
    sizes: [
      { size: 'S', stock: 8 },
      { size: 'M', stock: 14 },
      { size: 'L', stock: 18 },
      { size: 'XL', stock: 6 },
    ],
    stock: 46,
    tags: ['shirt', 'slim-fit', 'charcoal', 'formal'],
    isFeatured: true,
    isNewArrival: true,
    careInstructions: 'Machine wash cold. Iron on medium heat.',
  },
  {
    name: 'Chunky Platform Boots',
    slug: 'chunky-platform-boots',
    description: 'Bold chunky platform boots in matte black. Side zip closure with lug sole for extra grip.',
    category: 'Shoes',
    gender: 'Women',
    price: 6499,
    discountPrice: 4999,
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
      'https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=800',
    ],
    sizes: [
      { size: '5', stock: 4 },
      { size: '6', stock: 8 },
      { size: '7', stock: 10 },
      { size: '8', stock: 6 },
    ],
    stock: 28,
    tags: ['boots', 'platform', 'chunky', 'women'],
    isFeatured: false,
    isNewArrival: true,
    careInstructions: 'Wipe clean. Do not submerge in water.',
  },
];

export async function POST() {
  try {
    await dbConnect();

    // Check if products already exist
    const count = await Product.countDocuments();
    if (count > 0) {
      return NextResponse.json({ message: `Database already has ${count} products. Skipping seed.` });
    }

    await Product.insertMany(sampleProducts);

    return NextResponse.json({
      message: `Successfully seeded ${sampleProducts.length} products`,
      count: sampleProducts.length,
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: 'Failed to seed database' }, { status: 500 });
  }
}
